# Generated by Django 6.0.6 on 2026-06-23 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=10)),
                ('icon_svg', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('timezone', models.CharField(default='America/Monterrey', max_length=50)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Fellow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('fellow', 'Fellow'), ('mentor', 'Mentor'), ('exec', 'Executive')], default='fellow', max_length=10)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('project_description', models.TextField(blank=True)),
                ('current_phase', models.CharField(default='Orbit of Ideas', max_length=50)),
                ('xp_points', models.PositiveIntegerField(default=0)),
                ('google_access_token', models.TextField(blank=True)),
                ('google_refresh_token', models.TextField(blank=True)),
                ('google_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fellows', to='fellows.chapter')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fellows', to='fellows.cohort')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('team', 'Team'), ('personal', 'Personal')], default='personal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='pending', max_length=15)),
                ('source', models.CharField(choices=[('unbound', 'Assigned by UNbound'), ('self', 'Self-created')], default='self', max_length=10)),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('google_task_id', models.CharField(blank=True, max_length=200)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fellows.fellow')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='fellows.cohort')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FellowBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.BooleanField(default=False)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_badges', to='fellows.badge')),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='fellows.fellow')),
            ],
            options={
                'unique_together': {('fellow', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='MeetingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='fellows.fellow')),
            ],
            options={
                'ordering': ['day_of_week', 'hour'],
                'unique_together': {('fellow', 'day_of_week', 'hour')},
            },
        ),
    ]
