# Generated by Django 6.0.6 on 2026-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellow',
            name='selected_drive_folder_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fellow',
            name='selected_drive_folder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
