# Generated by Django 6.0.6 on 2026-07-23 21:50

import django.db.models.deletion
import fellows.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0002_fellow_selected_drive_folder_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fellows.models.generate_random_code, help_text='Unique invite code provided by Fellowship Execs.', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this code.', null=True)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Number of times this code can be used (default: 1).')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate code manually if needed.')),
                ('role', models.CharField(choices=[('fellow', 'Fellow'), ('mentor', 'Mentor'), ('exec', 'Executive')], default='fellow', max_length=10)),
                ('cohort', models.ForeignKey(blank=True, help_text='Cohort automatically assigned upon registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fellows.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
