# Generated by Django 6.0.6 on 2026-07-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0003_invitecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon_svg',
        ),
        migrations.AddField(
            model_name='badge',
            name='icon_class',
            field=models.CharField(default='fa-award', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='required_phase',
            field=models.CharField(blank=True, help_text='Phase required (e.g. Prototype, Graduation).', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='required_task_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of completed tasks required to unlock.'),
        ),
        migrations.AddField(
            model_name='badge',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='trigger_type',
            field=models.CharField(choices=[('task_count', 'Completed Task Count'), ('project_phase', 'Project Phase Reached'), ('availability', 'Meeting Availability Synced'), ('manual', 'Manual / Admin Awarded')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='xp_reward',
            field=models.PositiveIntegerField(default=100, help_text='XP awarded when badge is earned.'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=models.CharField(default='#00B4D8', max_length=20),
        ),
    ]
