# Generated by Django 6.0.6 on 2026-07-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0004_remove_badge_icon_svg_badge_icon_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='UN Goal Number (e.g., 3 for Good Health & Well-Being)', unique=True)),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(default='#00B4D8', max_length=20)),
            ],
            options={
                'verbose_name': 'SDG / UN Goal',
                'verbose_name_plural': 'SDGs / UN Goals',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='current_phase',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='project_name',
        ),
        migrations.AddField(
            model_name='cohort',
            name='current_phase',
            field=models.CharField(default='Orbit of Ideas', help_text='Current phase/status of the cohort project', max_length=50),
        ),
        migrations.AddField(
            model_name='cohort',
            name='project_description',
            field=models.TextField(blank=True, help_text="Detailed summary of the cohort's project"),
        ),
        migrations.AddField(
            model_name='cohort',
            name='project_name',
            field=models.CharField(blank=True, help_text="Name of the cohort's project", max_length=200),
        ),
        migrations.AddField(
            model_name='cohort',
            name='selected_sdgs',
            field=models.ManyToManyField(blank=True, help_text='Selected UN Sustainable Development Goals', related_name='cohorts', to='fellows.sdg'),
        ),
    ]
