# Generated by Django 6.0.6 on 2026-09-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0005_sdg_remove_fellow_current_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdg',
            name='code',
            field=models.PositiveIntegerField(help_text='UN Goal Number (1-17)', unique=True),
        ),
    ]
