# Generated by Django 6.0.6 on 2026-09-27 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0006_alter_sdg_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingavailability',
            options={'ordering': ['date', 'day_of_week', 'hour']},
        ),
        migrations.AlterUniqueTogether(
            name='meetingavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='meetingavailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingavailability',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AvailabilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Sprint 3 Sync Availability', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions or context for the fellows.')),
                ('start_date', models.DateField(help_text='Start date of the availability window.')),
                ('end_date', models.DateField(help_text='End date of the availability window.')),
                ('start_hour', models.PositiveSmallIntegerField(default=9, help_text='Starting hour (0-23, default 9 for 9 AM).')),
                ('end_hour', models.PositiveSmallIntegerField(default=18, help_text='Ending hour (0-23, default 18 for 6 PM).')),
                ('assign_to_all', models.BooleanField(default=False, help_text='If checked, this request applies to all active fellows regardless of cohort.')),
                ('deadline', models.DateField(blank=True, help_text='Optional submission deadline for fellows.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Active requests are visible in the fellows' Meeting Hub.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(blank=True, help_text='Target cohort. Leave blank if assigning to all fellows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_requests', to='fellows.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'When to Meet Request',
                'verbose_name_plural': 'When to Meet Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meetingavailability',
            name='availability_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='fellows.availabilityrequest'),
        ),
        migrations.AddField(
            model_name='task',
            name='availability_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fellows.availabilityrequest'),
        ),
        migrations.AddConstraint(
            model_name='meetingavailability',
            constraint=models.UniqueConstraint(fields=('availability_request', 'fellow', 'date', 'hour'), name='unique_availability_request_slot'),
        ),
        migrations.AddConstraint(
            model_name='meetingavailability',
            constraint=models.UniqueConstraint(condition=models.Q(('availability_request__isnull', True)), fields=('fellow', 'day_of_week', 'hour'), name='unique_legacy_availability_slot'),
        ),
    ]
